server:
  port: 8999

eureka:
  instance:
    hostname: localhost


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: hotel-management
          uri: lb://hotel-management
          predicates:
            - Path=/auth/**
        - id: hotel-management
          uri: lb://hotel-management
          predicates:
            - Path=/user/**
        - id: contactus
          uri: lb://contactus
          predicates:
            - Path=/contact/**